### PR TITLE
Optionally disable freeing federates when python weakrefs finalize

### PR DESCRIPTION
**Pull request by mtaylor-utilidata**
I saw the PR a couple days ago that allowed for turning off object freeing by the OS variable. I'd started this fork so I thought I'd PR it. Generally we wanted more granular control over whether federates are freed or not on finalize (rather than all objects or none) because in the service in which the federate is created we want the cleanup to be enacted generally (e.g. for messages) during finalize. However, because requests come in from Flask REST endpoints we need the federate itself to not be cleaned up on finalize. 

As a work around we are storing a reference to the federate in the flask container to prevent finalize from running. But, in the future we want to avoid manually managing static globally available helics objects like the federate when helics comes with the ability to register, store, and recall the federate through the capi.

### CODE REVIEW

**Comment by mtaylor-utilidata** [comment]
Follow up comment/disclaimer: To some extent I'm throwing this over the wall. I did try to keep in mind backwards compatibility in setting up defaults, etc. That said, I haven't thoroughly run tests, checked out the built artifacts, etc.. If considering this PR please take all needed precautions to ensure backwards compatibility and test coverage.

**Comment by kdheepak** [comment]
Would it not be possible for you to use the environment variable from the previous PR, and then manually manage memory everywhere?

i.e.

```bash
export PYHELICS_FREE_ON_DESTRUCTION=false
export PYHELICS_CLEANUP_ON_DESTRUCTION=false # optional because default is false
flask serve
```

```python
@app.route("/federate/<fed_name>")
def federate(fed_name):
    fed = h.helicsGetFederateByName(fed_name)
    ...
    # don't call h.helicsFederateFree(fed) if you don't want to free the federate
```

This is what the HELICS CAPI expects you to do.

I figured almost every average user would not need more than one federate, and a reference to that federate would be held for the rest of the program. Perhaps better documentation of this behavior and better logging would solve this problem?

**Comment by mtaylor-utilidata** [comment]
@kdheepak thanks for the quick response!

I think we want PYHELICS_FREE_ON_DESTRUCTION to be true for almost all objects, like messages. That is our default behavior that we want. But for federates that isn't the case, we want them to not free when GC. In your case above if PYHELICS_FREE_ON_DESTRUCTION is set to true then once we get the reference to `fed` (say to register more endpoints dynamically) we have to either maintain that reference even after the flask call has returned or do some serious surgery on on the object to reset its finalizer to not use the cleanup callback.

For context our flask method is roughly:
```
@app.route("/register-endpoints/{param1}/{param2}")
def federate(param1, param2):
    fed = h.helicsGetFederateByName(fed_name)
    # register a bunch of additional endpoints based on the params (before this federate enters execution mode) and return

```

It is true that we could manually free in the case of messages, and everything else. But that seems redundant and error prone to manually enforce the default behavior, while defaulting to the exception to the rule. This fork/PR just tries to invert that so we can set our default and then override in the single exception case of federate. 

No worries if this isn't accepted, but it seems like it would provide useful functionality for more advanced use-cases.

**Comment by kdheepak** [comment]
Let me think about it more and discuss it with @phlptp too. I imagine it might be okay to special case federates like you are suggesting, but with another environment variable instead.

**Comment by phlptp** [comment]
For the HELICS library itself all freeing is explicit, so it should be possible to use the c library more directly instead of the pythonic interface.  But if you want some of the nice features of the pythonic interface, and flag which disables all automatic destruction calls in python is probably appropriate to have.

**Comment by kdheepak** [comment]
Of all the `free` functions

```
helicsFederateFree
helicsFederateInfoFree
helicsBrokerFree
helicsCoreFree
helicsQueryFree
helicsMessageFree
```

in Python, I think query, message and federateinfo can be "free"d when the variable goes out of scope by default. Freeing Broker, Core, and Federate seem like they'll cause unnecessary hangs if done accidentally.

Thoughts @phlptp. Do you imagine a situation where calling free on Query, Message, or FederateInfo would cause a hang?

**Comment by phlptp** [comment]
FederateInfo yes
Query yes
those should be fine to call free automatically

Message,  there might be some care needed around the custom filter callback.  

The others all have means of retrieving an existing object, so automatically calling free or destroy on them is potentially problematic and could lead to unexpected behavior.

**Comment by kdheepak** [comment]
I'm thinking I should change it to default to _not_ destruct federates, brokers, cores and messages then.

**Comment by phlptp** [comment]
We should probably walk through this,  what I don't know is how much users are now relying on this feature.  

And messages my suspicion would be ok to have the default but I would need to see the details of how you handle the custom filter callback in python

**Comment by phlptp** [comment]
as we are talking about this, there might also be a similar issue in the C++98 API that I should explore a bit more.   We might also at least look into changing the C++ objects so free could always be called.

**Comment by phlptp** [comment]
What does the python destructor look like currently?

**Comment by phlptp** [comment]
Ok,  poked through the code a while.  I think the appropriate thing to do in python would be to always call the free method.    Inside Helics there is a reference counted object that manages the underlying object.  The object that has a link in the C world is a unique object and can be freed without any issues as long as there is multiple copies.    Python should not be calling destroy, disconnect or finalize by default though.     I think the missing feature in the C library would be a `helicsFederateLock`  or keep method that would keep the federate in memory if you are not going to maintain a local object copy.    Then as long as finalize or destroy wasn't called the federate should be able to be found and will run just fine.

**Pull request closed without merging**
