### PR TITLE
Quick bug fix for inputGetBytes()

### PR DESCRIPTION
**Pull request by plimy**
single line of code to fix helicsInputGetBytes() return.

### CODE REVIEW

**Comment by kdheepak** [comment]
Would you be able to add a test for this as well?

**Comment by kdheepak** [comment]
Fixes #31

**Comment by plimy** [comment]
I'll get a unit test written for it.

**Comment by kdheepak** [comment]
Thanks!

**Comment by kdheepak** [comment]
Thanks for the PR with tests! I’ll make a new release shortly.

**Pull request merged**
