### PR TITLE
Add HELICS 3.5.1 RECONNECTABLE handle option

### PR DESCRIPTION
**Pull request by nightlark**

### CODE REVIEW

**Comment by phlptp** [comment]
The changes look fine but  do we know why all the checks are failing?

**Comment by nightlark** [comment]
I don't see any connection between the test that that is segfaulting and the changed enums.

**Comment by phlptp** [comment]
I don't either but probably isn't good that all the tests are failing?

**Comment by nightlark** [comment]
It seems to be the addition of the RECONNECTABLE option that is making them seg fault.

**Comment by phlptp** [comment]
those tests that are failing, check a return on the pythonic api that references the flags somehow.  My guess is that is the issue somehow.   And maybe that flag needs to get added to the pythonic api

**Comment by nightlark** [comment]
It's specifically when the line `RECONNECTABLE = 412  # HelicsHandleOptions` gets added to the class that it fails.

**Comment by phlptp** [comment]
well I am not opposed to leaving it out for the time being.   That option was not needed for current python applications.

**Comment by nightlark** [comment]
Oh... I get it now. It was related to the assert -- some of the tests use `repr` to get a stringified representation of a Python object. I'm opening an issue to rewrite some of those test asserts; it seems like a quick way to check that the returned object is what is expected, but extremely fragile and makes adding a simple enum option require some not so intuitive updates to multiple API test asserts.

**Review by phlptp — APPROVED** [review]

**Pull request merged**
